server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_jpa_mini_project
    username: postgres
    password: Huy240419
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql